name: Continuous Integration

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  version:
    name: Bump Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - run: |
          git config --global user.name 'CI/CD'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch -m "Bump: %s"
          git push

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "Lint"
        run: |
          git config --global user.name 'CI/CD'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          bun lint || true
          git commit -am "Eslint: fix all" || true
          git push || true

  docker:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    needs:
      - version
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build . -t jmer05/electron-update-server:latest \
                         -t jmer05/electron-update-server:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push jmer05/electron-update-server:latest
          docker push jmer05/electron-update-server:${{ github.sha }}
